import { ProductCategory, Product } from "@/types/product";
import { Order } from "@/types/order";
import { UserProfile } from "@/types/user";

export const MOCK_CATEGORIES: ProductCategory[] = [
  {
    id: "cat-1",
    name: "Công Nghệ & Âm Thanh",
    nameEn: "Tech & Audio",
    slug: "tech-audio",
    description: "Tai nghe Hi-Fi, loa không dây, thiết bị âm thanh tinh tế",
    imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80",
    itemCount: 48,
  },
  {
    id: "cat-2",
    name: "Thời Trang & May Mặc",
    nameEn: "Apparel & Fashion",
    slug: "fashion",
    description: "Bộ sưu tập tối giản, chất liệu cao cấp và chuẩn phom dáng",
    imageUrl: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&auto=format&fit=crop&q=80",
    itemCount: 92,
  },
  {
    id: "cat-3",
    name: "Đồng Hồ & Trang Sức",
    nameEn: "Watches & Jewelry",
    slug: "watches",
    description: "Cỗ máy thời gian Thụy Sỹ, vòng tay chế tác thủ công",
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    itemCount: 35,
  },
  {
    id: "cat-4",
    name: "Không Gian Sống & Nội Thất",
    nameEn: "Living & Workspace",
    slug: "living",
    description: "Bàn làm việc gỗ óc chó, đèn chiếu sáng kiến trúc và phụ kiện",
    imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80",
    itemCount: 64,
  },
  {
    id: "cat-5",
    name: "Phụ Kiện Da Cao Cấp",
    nameEn: "Leather Goods",
    slug: "leather",
    description: "Ví da thủ công, túi xách du lịch da thuộc thảo mộc",
    imageUrl: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80",
    itemCount: 29,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "Tai Nghe Chống Ồn Không Dây OKZ Studio Master One",
    titleEn: "OKZ Studio Master One Wireless Noise-Cancelling Headphones",
    slug: "tai-nghe-chong-on-okz-studio-master-one",
    brand: "OKZ Audio",
    category: MOCK_CATEGORIES[0],
    price: 8490000,
    originalPrice: 9990000,
    rating: 4.9,
    reviewCount: 142,
    soldCount: 860,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    shortDescription: "Chất âm chuẩn phòng thu, driver 45mm mạ Beryllium, chống ồn chủ động Hybrid ANC 48dB.",
    shortDescriptionEn: "Studio-grade acoustics, 45mm Beryllium driver, 48dB Hybrid ANC with 40h battery.",
    description: "OKZ Studio Master One đại diện cho đỉnh cao chế tác tai nghe cao cấp. Vỏ nhôm nguyên khối hàng không kết hợp đệm tai da cừu mềm mại đem đến cảm giác đeo êm ái suốt cả ngày. Công nghệ AI Spatial Audio tự động định vị âm thanh 3D sống động theo chuyển động đầu.",
    descriptionEn: "The OKZ Studio Master One represents the pinnacle of premium headphone craftsmanship. Aviation-grade aluminum unibody paired with lambskin ear cushions ensures all-day comfort. Integrated AI Spatial Audio delivers true-to-life 3D soundscapes.",
    thumbnail: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=1000&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=1000&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=1000&auto=format&fit=crop&q=80",
    ],
    specs: {
      "Thời lượng pin": "40 giờ (bật ANC)",
      "Chuẩn kết nối": "Bluetooth 5.4, aptX Lossless, LDAC",
      "Chống ồn": "Hybrid Active Noise Cancelling 48dB",
      "Trọng lượng": "278g",
      "Chất liệu": "Nhôm Anodized & Da cừu tự nhiên",
    },
    specsEn: {
      "Battery Life": "40 hours (ANC On)",
      "Connectivity": "Bluetooth 5.4, aptX Lossless, LDAC",
      "Noise Cancellation": "Hybrid Active Noise Cancelling 48dB",
      "Weight": "278g",
      "Materials": "Anodized Aluminum & Genuine Lambskin",
    },
    variants: [
      {
        id: "var-1-1",
        sku: "OKZ-H1-BLK",
        name: "Đen Midnight",
        nameEn: "Midnight Black",
        price: 8490000,
        originalPrice: 9990000,
        stock: 25,
        options: { color: "Midnight Black" },
      },
      {
        id: "var-1-2",
        sku: "OKZ-H1-SLV",
        name: "Bạc Ánh Kim",
        nameEn: "Titanium Silver",
        price: 8490000,
        originalPrice: 9990000,
        stock: 14,
        options: { color: "Titanium Silver" },
      },
      {
        id: "var-1-3",
        sku: "OKZ-H1-MNT",
        name: "Xanh Mint Aloe",
        nameEn: "Aloe Mint Edition",
        price: 8890000,
        originalPrice: 10490000,
        stock: 8,
        options: { color: "Aloe Mint" },
      },
    ],
    reviews: [
      {
        id: "rev-1",
        userId: "u-101",
        userName: "Trần Minh Quang",
        rating: 5,
        comment: "Âm trường cực kỳ rộng, dải bass kiểm soát chắc nịch và micro lọc tiếng ồn khi họp online rất rõ.",
        commentEn: "Incredible soundstage, punchy controlled bass, and microphone noise-filtering is top-notch for meetings.",
        createdAt: "2026-08-10T14:30:00Z",
        verifiedPurchase: true,
        likesCount: 18,
      },
      {
        id: "rev-2",
        userId: "u-102",
        userName: "Lê Thu Hà",
        rating: 5,
        comment: "Bản màu Aloe Mint ở ngoài đẹp hơn cả ảnh chụp! Đệm tai da cừu đeo 4 tiếng liên tục không hề bị đau vành tai.",
        commentEn: "The Aloe Mint edition looks even more stunning in person! Lambskin cushions are super gentle.",
        createdAt: "2026-08-05T09:15:00Z",
        verifiedPurchase: true,
        likesCount: 9,
      },
    ],
    tags: ["Audio", "Wireless", "ANC", "Premium"],
    stock: 47,
  },
  {
    id: "prod-2",
    title: "Đồng Hồ Cơ Automatic OKZ Chrono Heritage 40mm",
    titleEn: "OKZ Chrono Heritage 40mm Automatic Watch",
    slug: "dong-ho-co-automatic-okz-chrono-heritage",
    brand: "OKZ Horology",
    category: MOCK_CATEGORIES[2],
    price: 16500000,
    originalPrice: 18900000,
    rating: 5.0,
    reviewCount: 88,
    soldCount: 320,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    shortDescription: "Bộ máy cơ tự động Thụy Sỹ Calibre OKZ-900, mặt kính Sapphire chống lóa kép, chống nước 10ATM.",
    shortDescriptionEn: "Swiss Automatic Calibre OKZ-900 movement, double AR-coated Sapphire crystal, 10ATM water resistance.",
    description: "Chrono Heritage mang dáng dấp đồng hồ phi công cổ điển được tái định nghĩa theo thẩm mỹ đương đại. Mặt số vân Guilloché thủ công, kim nung xanh nhiệt độ cao và vỏ thép không gỉ 316L đánh bóng mờ tinh xảo.",
    descriptionEn: "Chrono Heritage merges vintage aviation aesthetics with modern horological design. Handcrafted Guilloché dial, heat-blued steel hands, and a brushed 316L stainless steel case.",
    thumbnail: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=1000&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=1000&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=1000&auto=format&fit=crop&q=80",
    ],
    specs: {
      "Bộ máy": "Automatic Swiss Calibre (Trữ cót 48h)",
      "Đường kính mặt": "40mm (Độ dày 10.8mm)",
      "Mặt kính": "Sapphire nguyên khối phủ AR chống chói",
      "Chống nước": "100m (10 ATM)",
      "Dây đeo": "Da bê Ý vân tự nhiên 20mm",
    },
    specsEn: {
      "Movement": "Automatic Swiss Calibre (48h Power Reserve)",
      "Case Diameter": "40mm (Thickness 10.8mm)",
      "Glass": "Solid Sapphire with Double AR Coating",
      "Water Resistance": "100m (10 ATM)",
      "Strap": "20mm Genuine Italian Calfskin",
    },
    variants: [
      {
        id: "var-2-1",
        sku: "OKZ-W-SLV",
        name: "Mặt Trắng Bạc / Dây Nâu",
        nameEn: "Silver Dial / Brown Strap",
        price: 16500000,
        originalPrice: 18900000,
        stock: 12,
        options: { color: "Silver / Brown" },
      },
      {
        id: "var-2-2",
        sku: "OKZ-W-BLK",
        name: "Mặt Đen Dạ Quang / Dây Đen",
        nameEn: "Obsidian Dial / Black Strap",
        price: 16900000,
        originalPrice: 19500000,
        stock: 9,
        options: { color: "Obsidian Black" },
      },
    ],
    reviews: [
      {
        id: "rev-201",
        userId: "u-201",
        userName: "Nguyễn Hải Đăng",
        rating: 5,
        comment: "Đồng hồ chạy cực kỳ chính xác sai số chỉ khoảng +2s/ngày. Đóng gói hộp gỗ cao cấp rất sang trọng.",
        commentEn: "Extremely accurate running at ~+2s/day. The wooden presentation box is truly luxury.",
        createdAt: "2026-07-28T16:20:00Z",
        verifiedPurchase: true,
        likesCount: 14,
      },
    ],
    tags: ["Watch", "Luxury", "Automatic", "Sapphire"],
    stock: 21,
  },
  {
    id: "prod-3",
    title: "Túi Xách Da Du Lịch Tuần OKZ Nomad Leather Duffle 45L",
    titleEn: "OKZ Nomad Leather Weekend Duffle Bag 45L",
    slug: "tui-xach-du-lich-da-okz-nomad-duffle-45l",
    brand: "OKZ Atelier",
    category: MOCK_CATEGORIES[4],
    price: 6800000,
    originalPrice: 7900000,
    rating: 4.8,
    reviewCount: 64,
    soldCount: 450,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    shortDescription: "Da bò Full-grain thuộc thảo mộc Ý, khóa kéo YKK Excella mạ vàng mờ, ngăn chống sốc laptop 16 inch.",
    shortDescriptionEn: "Full-grain Italian vegetable-tanned leather, YKK Excella brass zippers, padded 16\" laptop sleeve.",
    description: "Được thiết kế cho những chuyến công tác hoặc kỳ nghỉ cuối tuần tinh tế. Da thuộc tự nhiên càng dùng càng lên nước bóng patina độc nhất vô nhị. Quai đeo có đệm phân tán lực và đáy gia cố 6 chân đinh kim loại.",
    descriptionEn: "Engineered for discerning weekend getaways and business travels. Naturally tanned leather patinas beautifully over time.",
    thumbnail: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1000&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=1000&auto=format&fit=crop&q=80",
    ],
    specs: {
      "Dung tích": "45 Lít",
      "Kích thước": "52 x 28 x 26 cm",
      "Chất liệu da": "Full-grain Italian Vachetta Leather",
      "Trọng lượng": "1.75 kg",
    },
    specsEn: {
      "Capacity": "45 Liters",
      "Dimensions": "52 x 28 x 26 cm",
      "Leather": "Full-grain Italian Vachetta Leather",
      "Weight": "1.75 kg",
    },
    variants: [
      {
        id: "var-3-1",
        sku: "OKZ-BAG-COGNAC",
        name: "Nâu Cognac Cổ Điển",
        nameEn: "Classic Cognac",
        price: 6800000,
        originalPrice: 7900000,
        stock: 18,
        options: { color: "Cognac Brown" },
      },
      {
        id: "var-3-2",
        sku: "OKZ-BAG-BLK",
        name: "Đen Matte Nappa",
        nameEn: "Matte Nappa Black",
        price: 6800000,
        originalPrice: 7900000,
        stock: 11,
        options: { color: "Matte Black" },
      },
    ],
    reviews: [],
    tags: ["Leather", "Travel", "Duffle", "Handcrafted"],
    stock: 29,
  },
  {
    id: "prod-4",
    title: "Đèn Bàn Kiến Trúc OKZ Halo Linear Light",
    titleEn: "OKZ Halo Linear Architectural Desk Lamp",
    slug: "den-ban-kien-truc-okz-halo-linear-light",
    brand: "OKZ Living",
    category: MOCK_CATEGORIES[3],
    price: 3890000,
    originalPrice: 4500000,
    rating: 4.9,
    reviewCount: 95,
    soldCount: 510,
    isFeatured: false,
    isNew: true,
    isBestSeller: true,
    shortDescription: "CRI 98+ chuẩn màu chuyên gia thiết kế, cảm biến chạm xoay vô cực, hỗ trợ sạc nhanh không dây Qi2 15W.",
    shortDescriptionEn: "CRI 98+ color accuracy for designers, infinite dial touch sensor, built-in Qi2 15W wireless charger.",
    description: "OKZ Halo Linear chiếu rọi không gian làm việc với dải quang phổ mô phỏng ánh sáng mặt trời tự nhiên, giảm mỏi mắt khi làm việc ban đêm. Tích hợp sạc không dây nam châm ở chân đế.",
    descriptionEn: "Simulates natural daylight spectrum to reduce eye strain during prolonged sessions. Base features an integrated wireless charging pad.",
    thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=1000&auto=format&fit=crop&q=80",
    ],
    specs: {
      "Chỉ số hoàn màu": "CRI Ra > 98",
      "Nhiệt độ màu": "2700K - 6500K (Tùy chỉnh)",
      "Độ sáng tối đa": "1200 Lux",
      "Tính năng thêm": "Đế sạc không dây 15W Qi2",
    },
    specsEn: {
      "Color Rendering Index": "CRI Ra > 98",
      "Color Temperature": "2700K - 6500K (Adjustable)",
      "Max Brightness": "1200 Lux",
      "Extra Feature": "15W Qi2 Wireless Fast Charger",
    },
    variants: [
      {
        id: "var-4-1",
        sku: "OKZ-LAMP-BLK",
        name: "Đen Anodized",
        nameEn: "Anodized Black",
        price: 3890000,
        originalPrice: 4500000,
        stock: 30,
        options: { color: "Anodized Black" },
      },
    ],
    reviews: [],
    tags: ["Workspace", "Lighting", "Minimalist", "Design"],
    stock: 30,
  },
  {
    id: "prod-5",
    title: "Áo Khoác Blazer Len Merino Dệt Thủ Công OKZ Sartorial",
    titleEn: "OKZ Sartorial Hand-Woven Merino Wool Blazer",
    slug: "ao-khoac-blazer-len-merino-okz-sartorial",
    brand: "OKZ Sartorial",
    category: MOCK_CATEGORIES[1],
    price: 5200000,
    originalPrice: 6200000,
    rating: 4.7,
    reviewCount: 39,
    soldCount: 210,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    shortDescription: "100% sợi len Extra-fine Merino Super 130s, cấu trúc không đệm vai mềm mại, lót lụa tơ tằm thoáng khí.",
    shortDescriptionEn: "100% Super 130s Extra-fine Merino Wool, unstructured soft shoulder construction, silk lining.",
    description: "Chiếc blazer chuẩn may đo cao cấp phong cách Ý (Neapolitan cut). Trọng lượng vải nhẹ thích hợp cho cả 4 mùa trong năm.",
    descriptionEn: "Bespoke Italian Neapolitan tailoring cut with featherlight natural drape suitable for year-round wear.",
    thumbnail: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1000&auto=format&fit=crop&q=80",
    ],
    specs: {
      "Chất liệu": "100% Super 130s Merino Wool",
      "Kiểu dáng": "Slim-tailored / Unstructured",
      "Xuất xứ vải": "Biella, Italy",
    },
    specsEn: {
      "Material": "100% Super 130s Merino Wool",
      "Fit": "Slim-tailored / Unstructured",
      "Fabric Origin": "Biella, Italy",
    },
    variants: [
      {
        id: "var-5-1",
        sku: "OKZ-BLZ-48",
        name: "Size 48 (M) - Xanh Navy",
        nameEn: "Size 48 (M) - Navy Blue",
        price: 5200000,
        originalPrice: 6200000,
        stock: 6,
        options: { size: "48", color: "Navy" },
      },
      {
        id: "var-5-2",
        sku: "OKZ-BLZ-50",
        name: "Size 50 (L) - Xanh Navy",
        nameEn: "Size 50 (L) - Navy Blue",
        price: 5200000,
        originalPrice: 6200000,
        stock: 10,
        options: { size: "50", color: "Navy" },
      },
    ],
    reviews: [],
    tags: ["Fashion", "Blazer", "Merino", "Luxury"],
    stock: 16,
  },
  {
    id: "prod-6",
    title: "Loa Bluetooth Không Dây OKZ Studio Sound Sphere 360",
    titleEn: "OKZ Studio Sound Sphere 360 Wireless Speaker",
    slug: "loa-bluetooth-khong-day-okz-sound-sphere-360",
    brand: "OKZ Audio",
    category: MOCK_CATEGORIES[0],
    price: 4990000,
    originalPrice: 5800000,
    rating: 4.8,
    reviewCount: 77,
    soldCount: 640,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    shortDescription: "Âm thanh vòm 360 độ công suất 80W, vỏ vải dệt Kvadrat Đan Mạch, chống nước IPX7.",
    shortDescriptionEn: "360-degree omni sound with 80W output, Danish Kvadrat fabric grille, IPX7 waterproof.",
    description: "Mang âm nhạc lan tỏa đồng đều khắp mọi góc phòng. Thời lượng pin 24 giờ liên tục và công nghệ ghép đôi 2 loa Stereo không dây.",
    descriptionEn: "Spreads acoustic richness across every corner with true 360 omnidirectional dispersion.",
    thumbnail: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=1000&auto=format&fit=crop&q=80",
    ],
    specs: {
      "Công suất": "80W RMS (Peak 120W)",
      "Chuẩn chống nước": "IPX7",
      "Thời lượng pin": "24 giờ",
    },
    specsEn: {
      "Output Power": "80W RMS (Peak 120W)",
      "Waterproof": "IPX7",
      "Battery Life": "24 hours",
    },
    variants: [
      {
        id: "var-6-1",
        sku: "OKZ-SPK-MNT",
        name: "Xanh Aloe Mint",
        nameEn: "Aloe Mint",
        price: 4990000,
        originalPrice: 5800000,
        stock: 20,
        options: { color: "Aloe Mint" },
      },
      {
        id: "var-6-2",
        sku: "OKZ-SPK-GRY",
        name: "Xám Bão Sandy Grey",
        nameEn: "Sandy Grey",
        price: 4990000,
        originalPrice: 5800000,
        stock: 15,
        options: { color: "Sandy Grey" },
      },
    ],
    reviews: [],
    tags: ["Audio", "Speaker", "360Sound", "Wireless"],
    stock: 35,
  },
];

export const MOCK_USER: UserProfile = {
  id: "user-demo-01",
  fullName: "Bùi Hoàng Nam",
  email: "hoangnam.bui@example.com",
  phone: "0912 345 678",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
  gender: "male",
  birthday: "1994-06-18",
  membershipTier: "Platinum",
  addresses: [
    {
      id: "addr-1",
      fullName: "Bùi Hoàng Nam",
      phone: "0912 345 678",
      email: "hoangnam.bui@example.com",
      province: "Thành phố Hồ Chí Minh",
      district: "Quận 1",
      ward: "Phường Bến Nghé",
      streetAddress: "Tầng 18, Tòa nhà Landmark 81, 720A Điện Biên Phủ",
      isDefault: true,
    },
    {
      id: "addr-2",
      fullName: "Bùi Hoàng Nam (Văn phòng)",
      phone: "0912 345 678",
      province: "Hà Nội",
      district: "Quận Hoàn Kiếm",
      ward: "Phường Tràng Tiền",
      streetAddress: "Số 24 Tràng Tiền Plaza",
      isDefault: false,
    },
  ],
  savedCards: [
    {
      id: "card-1",
      cardType: "visa",
      last4: "8899",
      holderName: "BUI HOANG NAM",
      expiry: "08/29",
      isDefault: true,
    },
  ],
};

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-882194",
    orderNumber: "OKZ-2026-882194",
    createdAt: "2026-08-14T10:30:00Z",
    status: "PROCESSING",
    paymentMethod: "BANK_TRANSFER",
    paymentStatus: "PAID",
    shippingAddress: MOCK_USER.addresses[0],
    items: [
      {
        id: "oi-1",
        productId: "prod-1",
        productTitle: "Tai Nghe Chống Ồn Không Dây OKZ Studio Master One",
        productTitleEn: "OKZ Studio Master One Wireless Noise-Cancelling Headphones",
        thumbnail: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop&q=80",
        price: 8490000,
        quantity: 1,
        variantName: "Xanh Mint Aloe",
        variantNameEn: "Aloe Mint Edition",
      },
    ],
    subtotal: 8490000,
    shippingFee: 0,
    discountAmount: 500000,
    voucherCode: "OKZVIP",
    total: 7990000,
    timeline: [
      {
        status: "PENDING",
        title: "Đơn hàng đã được tạo",
        titleEn: "Order placed successfully",
        description: "Khách hàng đã đặt đơn và thanh toán chuyển khoản thành công.",
        descriptionEn: "Payment confirmed via instant wire transfer.",
        timestamp: "2026-08-14 10:30",
        isCompleted: true,
      },
      {
        status: "PROCESSING",
        title: "Đang đóng gói và kiểm định",
        titleEn: "Inspection and Packing",
        description: "Bộ phận kho đang kiểm tra số serial và đóng gói chống sốc.",
        descriptionEn: "Warehouse is inspecting quality and packing.",
        timestamp: "2026-08-14 14:15",
        isCompleted: true,
        isCurrent: true,
      },
      {
        status: "SHIPPED",
        title: "Bàn giao đơn vị vận chuyển",
        titleEn: "Handed over to Courier",
        description: "Shipper Hỏa Tốc sẽ liên hệ giao hàng trong 2-4 giờ.",
        descriptionEn: "Express courier will deliver soon.",
        timestamp: "Dự kiến 2026-08-15",
        isCompleted: false,
      },
      {
        status: "DELIVERED",
        title: "Giao hàng thành công",
        titleEn: "Delivered",
        description: "Người nhận đã ký xác nhận nhận hàng.",
        descriptionEn: "Delivered and signed by recipient.",
        timestamp: "Dự kiến 2026-08-15",
        isCompleted: false,
      },
    ],
  },
  {
    id: "ord-881023",
    orderNumber: "OKZ-2026-881023",
    createdAt: "2026-08-01T15:20:00Z",
    status: "DELIVERED",
    paymentMethod: "CREDIT_CARD",
    paymentStatus: "PAID",
    shippingAddress: MOCK_USER.addresses[0],
    items: [
      {
        id: "oi-2",
        productId: "prod-4",
        productTitle: "Đèn Bàn Kiến Trúc OKZ Halo Linear Light",
        productTitleEn: "OKZ Halo Linear Architectural Desk Lamp",
        thumbnail: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&auto=format&fit=crop&q=80",
        price: 3890000,
        quantity: 1,
        variantName: "Đen Anodized",
        variantNameEn: "Anodized Black",
      },
    ],
    subtotal: 3890000,
    shippingFee: 0,
    discountAmount: 0,
    total: 3890000,
    timeline: [
      {
        status: "DELIVERED",
        title: "Giao hàng thành công",
        titleEn: "Delivered",
        description: "Đơn hàng đã được giao thành công cho khách hàng.",
        descriptionEn: "Delivered to customer successfully.",
        timestamp: "2026-08-03 11:20",
        isCompleted: true,
        isCurrent: true,
      },
    ],
  },
];
