export enum ApiErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  AI_PROVIDER_ERROR = 'AI_PROVIDER_ERROR',
  SQL_SAFETY_ERROR = 'SQL_SAFETY_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
